name: Actualizar datos NASA

on:
  schedule:
    - cron: '0 8 * * 1'
  workflow_dispatch:

jobs:
  actualizar:
    runs-on: ubuntu-latest

    steps:
      - name: Clonar repositorio
        uses: actions/checkout@v3

      - name: Configurar Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.11'

      - name: Instalar dependencias
        run: pip install requests pandas python-dotenv duckdb

      - name: Verificar descarga NASA
        run: python src/download_exoplanets.py
        env:
          NASA_API_KEY: ${{ secrets.NASA_API_KEY }}